Add support for vertx-like ssl options
vert-x3/vertx-ignite pull request #106
Opened 2021-01-29 19:18 UTC by zyclonite

Motivation:

Unify eventbus and cluster manager ssl options.
Allows usage of the same certificates for clustering vertx securely.

Flags old config options as deprecated and to be removed in version 4.1

2021-02-01 12:09 UTC, zyclonite commented
@tsegismont what do you think?
https://github.com/vert-x3/vertx-ignite/blob/4583739934a3f69d4d938d1c00b757c9103a7bf1/src/main/java/examples/Examples.java#L65-L96

2021-02-02 10:01 UTC, vietj commented
can we merge this PR for 4.0.1 ?

2021-02-02 15:36 UTC, zyclonite commented
if @tsegismont or you are fine with this approach, yes definitely

2021-02-02 16:02 UTC, tsegismont requested changes
@zyclonite thank you, that's a good idea I think, provided we keep the compatibility with the previous options format.

I have a few concerns but nothing big.

2021-02-02 16:02 UTC, tsegismont commented on src/main/java/io/vertx/spi/cluster/ignite/IgniteOptions.java
> +  public IgniteConfiguration toConfig(Vertx vertx) {
Can you move this method to the Ignite CM impl and update the breaking changes page?

Such conversion methods are better placed out of the public API.

2021-02-02 17:07 UTC, zyclonite commented on src/main/java/examples/Examples.java
> +      .setSslContextFactory(new IgniteSslOptions()
I know this is a bit confusing ... I tried to stick as near as possible to the original config terms but use internally the `Options` objects that handle the JSON objects

The config can be rebuilt from a JSON object but you can't pass the SslContextFactory as an object in that case
This will be cleaned up with Ignite 3.0 were there will be a native mapping for JSON configs

2021-02-02 17:25 UTC, zyclonite commented on src/main/java/io/vertx/spi/cluster/ignite/IgniteOptions.java
> +  public IgniteConfiguration toConfig(Vertx vertx) {
makes sense, moved it into the ConfigHelper to not overload the CM impl

2021-02-02 17:27 UTC, zyclonite commented
thank you for the quick feedback
i updated the breaking changes wiki page and implemented your suggestions

2021-02-03 09:47 UTC, tsegismont approved these changes
LGTM, thank you @zyclonite !

2021-02-03 09:49 UTC, merged