Perf improvements in subscription event handling
vert-x3/vertx-ignite pull request #111
Opened 2021-03-10 20:36 UTC by zyclonite

Follows-up on eclipse-vertx/vert.x#3843

The improvements mostly consist in:

* keeping local consumers data on the node
  This reduces the traffic and prevents for notifying other nodes (which are not interested anyway).

* throttling of local subscription events
  This reduces traffic and load on all nodes

Related to eclipse-vertx/vert.x#3797

2021-03-11 14:54 UTC, tsegismont requested changes

2021-03-11 14:54 UTC, tsegismont commented on src/main/java/io/vertx/spi/cluster/ignite/impl/SubsMapHelper.java
> +    if (nodeSelector.wantsUpdatesFor(address)) {
Minor but you could spare the creation of the promise/future by moving this inside the creation inside this test body

2021-03-11 14:54 UTC, tsegismont commented on src/main/java/io/vertx/spi/cluster/ignite/impl/SubsMapHelper.java
> +    throttling = new Throttling(vertxInternal, this::getAndUpdate);
The `getAndUpdate` method is asynchronous but this version of the `Throttling` class has been built a synchronous action.

Check out the `vertx-infinispan` version of `Throttling` and its usage.

2021-03-11 17:08 UTC, zyclonite commented on src/main/java/io/vertx/spi/cluster/ignite/impl/SubsMapHelper.java
> +    if (nodeSelector.wantsUpdatesFor(address)) {
yes you are right

2021-03-11 17:08 UTC, zyclonite commented on src/main/java/io/vertx/spi/cluster/ignite/impl/SubsMapHelper.java
> +    throttling = new Throttling(vertxInternal, this::getAndUpdate);
uh, i will take a look thank you

2021-03-11 22:52 UTC, tsegismont approved these changes
LGTM, ship it!

2021-03-11 22:55 UTC, tsegismont commented
@zyclonite I'll let you merge in case you want to add anything minor beforehand.

@vietj please hold off releasing before this one is merged

2021-03-12 10:45 UTC, merged

2021-03-12 10:46 UTC, DemonicTutor commented
yeppie!